version: "3.8"
services:
    app:
        build:
            args:
                user: Alibaba
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: articles
        container_name: articles-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - net

    db:
        image: mysql:latest
        container_name: articles-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: transport-management-mysql
        volumes:
            - ./docker/mysql:/docker-entrypoint-initdb.d
        ports:
            - 3308:3306
        networks:
            - net

    webserver:
        image: nginx:alpine
        container_name: articles-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - net


networks:
    net:
        driver: bridge
